[kijanikiosk]
api-staging ansible_host=13.247.245.205
payments-staging ansible_host=13.245.197.149
logs-staging ansible_host=13.247.89.33

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/kijanikiosk-key-aws.pem