apiVersion: v1
kind: Service
metadata:
  name: kk-payments-service
  labels:
    app: kk-payments
spec:
  type: NodePort # Exposes a port on every cluster node
  selector:
    app: kk-payments # Routes to all Pods with this label. Same label used in the Deployment template
  ports:
    - name: http
      protocol: TCP
      port: 3001 # Port on the Service's ClusterIP (internal cluster access)
      targetPort: 3001 # Port on the Pod (must match containerPort in Deployment)
      nodePort: 30001
