[kijanikiosk]
api-staging ansible_host=16.28.109.89
payments-staging ansible_host=16.28.97.41
logs-staging ansible_host=16.28.64.244

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/lewis/.ssh/kijanikiosk-key-aws.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
