[kijanikiosk]
api-staging ansible_host=13.244.102.15
payments-staging ansible_host=13.246.198.208
logs-staging ansible_host=13.247.177.24

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/lewis/.ssh/kijanikiosk-key-aws.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
