[kijanikiosk]
api-staging ansible_host=13.244.109.156
payments-staging ansible_host=13.247.119.215
logs-staging ansible_host=13.247.180.236

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/lewis/.ssh/kijanikiosk-key-aws.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
